const data = {
    products: [
        {
            _id: '1',
            name: 'Tie Back Print Sundress',
            category: 'Dresses',
            image: '/images/p-1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Nike',
            rating: 5,
            numReviews: 10,
            description: 'High quality  product',
        },
        {
            _id: '2',
            name: "What's Hot What Not?",
            category: 'Dresses',
            image: '/images/p-2.jpg',
            price: 70,
            countInStock: 20,
            brand: 'Puma',
            rating: 4,
            numReviews: 20,
            description: 'High quality  product',
        },
        {
            _id: '3',
            name: 'Long to Short Light Weight',
            category: 'Dresses',
            image: '/images/p-3.jpg',
            price: 100,
            countInStock: 5,
            brand: 'Lakoste',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality  product',
        },
        {
            _id: '4',
            name: 'Vacation Beach Mini Dress',
            category: 'Dresses',
            image: '/images/p-4.jpg',
            price: 130,
            countInStock: 0,
            brand: 'Nike',
            rating: 5,
            numReviews: 12,
            description: 'High quality  product',
        },
        {
            _id: '5',
            name: 'Reformation Skirt',
            category: 'Dresses',
            image: '/images/p-5.jpg',
            price: 80,
            countInStock: 50,
            brand: 'Puma',
            rating: 3.5,
            numReviews: 5,
            description: 'High quality  product',
        },
        {
            _id: '6',
            name: 'Fashion-Young-Woman',
            category: 'Dresses',
            image: '/images/p-6.jpg',
            price: 150,
            countInStock: 15,
            brand: 'Adidas',
            rating: 5,
            numReviews: 18,
            description: 'High quality  product',
        },
    ],
};
export default data;